[package]
name = "why3-ptree"
version = "0.1.0"
edition = "2024"
license = "MIT or Apache-2.0"
repository = "https://github.com/temp66/why3-ptree-rust"
description = "A Rust port of the parse trees and related utilities from the Why3 OCaml API."

[package.metadata.docs.rs]
all-features = true

[lints.clippy]
type_complexity = "allow"

[dependencies]
bumpalo = "3.20.2"
internment = { version = "0.8.6", default-features = false, features = ["arc"] }
malachite = { version = "0.9.1", default-features = false, features = ["naturals_and_integers", "std"] }
ocaml-format = "0.1.1"
serde = { version = "1.0.228", features = ["derive"], optional = true }

[features]
serde = ["dep:serde", "internment/serde", "malachite/enable_serde"]
